Add CustomButton component and replace Button with CustomButton
CAMPUS-NYCU/SmartCampus pull request #60
Opened 2021-06-23 13:51 UTC by alexchen45

## Why do we need this PR?
* Button component is replaced with new CustomButton Component
* Color and shadows of buttons are altered.
## How did you address the issue?
*

2021-06-23 14:26 UTC, jiangxin1998 approved these changes

2021-06-24 01:56 UTC, KalleChen requested changes
Look great, but there is still something to be changed. And we should now follow the rule of eslint, please check eslint every time you create a PR.

2021-06-24 01:58 UTC, KalleChen requested changes
Look great, but there is still something to be changed. And we should now follow the rule of eslint, please check eslint every time you create a PR.

2021-06-24 01:58 UTC, KalleChen commented on src/utils/functions/ImageUpload.js
> +        children='選擇照片'
eslint

2021-06-24 01:58 UTC, KalleChen commented on src/pages/MapPage/components/Mission/MissionDrawer/MissionStepper.js
> +                children='確定'
eslint

2021-06-24 01:58 UTC, KalleChen commented on src/pages/MapPage/components/Mission/MissionDrawer/MissionStepper.js
> +              children='確定'
eslint

2021-06-24 01:58 UTC, KalleChen commented on src/pages/MapPage/components/Mission/MissionDrawer/MissionStep2/MissionStep2.js
> +              children={facility.subTypeName}
eslint

2021-06-24 01:58 UTC, KalleChen commented on src/pages/MapPage/components/Mission/MissionDrawer/MissionStep1/MissionStep1.js
> +          borderRadius='20px'
border-radius

2021-06-24 01:58 UTC, KalleChen commented on src/pages/MapPage/components/Filter/FilterDrawer.js
> +          borderRadius='20px'
border-radius should be write in the CustomButton file. If we have two version of border-radius, create a prop to choose which to use, we should not passing the style value here.

2021-06-24 01:58 UTC, KalleChen commented on src/pages/MapPage/components/Filter/FilterDrawer.js
> +                      children={discovery.targetName}
eslint

2021-06-24 01:58 UTC, KalleChen commented on src/pages/MapPage/components/Filter/FilterDrawer.js
> +                      children={discovery.subTypeName}
eslint

2021-06-24 01:58 UTC, KalleChen commented on src/pages/MapPage/components/Filter/FilterDrawer.js
> +                  children={mission.missionName}
elsint

2021-06-24 01:58 UTC, KalleChen commented on src/components/CustomDrawer/CustomDrawer.js
> +                  children={titleAction.name}
For eslint rule, do not pass children from props

2021-06-24 01:58 UTC, KalleChen commented on src/components/CustomDrawer/CustomDrawer.js
>    }
We should remove this here, the main goal of this feature is that we can only import the button and use it without create other styles.

2021-06-24 01:58 UTC, KalleChen commented on src/components/CustomButton/CustomButton.js
> +            borderRadius: borderRadius,
And the default style should be implemented with material ui's `withStyle` or `makeStyles`, you can check how CustomerDrawer does.

2021-06-24 01:58 UTC, KalleChen commented on src/components/CustomButton/CustomButton.js
> +                :{backgroundColor},
color and backgroundColor should be implemented in color prop `color={color}` and the color value is setting in the `theme.js`.

2021-06-29 06:49 UTC, KalleChen approved these changes

2021-06-29 06:59 UTC, merged